### ISSUE TITLE
Running dragon lo results in a crash

### ISSUE THREAD

**Issue by RUGMJ** [DragonBuild/DragonBuild#137]
`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/rugmj/.local/lib/python3.11/site-packages/dragon/lo.py", line 6, in <module>
    from dragon.util import dprintline, OutputColors, OutputWeight
ImportError: cannot import name 'dprintline' from 'dragon.util' (/home/rugmj/.local/lib/python3.11/site-packages/dragon/util.py)`

After looking at the source code it seems the imports dont exist in the utils module at all not really sure whats meant to be happening here

**Comment by RUGMJ** [comment]
seems the shared package has the correct util, changing dragon.util to shared.util would resolve this unless theres something im missing

**Comment by L1ghtmann** [comment]
Thanks for catching this. Will fix in an upcoming release. 

If you'd like to fix it locally, you can make the edits necessary to this repo and run the dev install script.
